### ISSUE TITLE
Function defined in a header

### ISSUE THREAD

**Issue by agagniere** [learn-orolia/skydel-remote-api#2]
In the header : `Cpp/sdx_api/hil_helper.h`,
the function `preciseSleepUntilMs` is defined without the `inline` keyword.

The recommended practice would be to place the definition in a `hil_helper.cpp` file, and keep only the declaration in the header.

The consequence of this definition in a header is that including `hil_helper.h` in more than one `.cpp` file causes a linker error

**Comment by Rouiller** [comment]
Fixed in release [23.11.0](https://github.com/learn-safran-navigation-timing/skydel-remote-api/releases/tag/v23.11.0).
